# Generated by Django 6.0.7 on 2026-07-31 19:30

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models

import netbox_ledger_tracker.models


class Migration(migrations.Migration):
    dependencies = [
        ('extras', '0140_imageattachment_image_size'),
        ('netbox_ledger_tracker', '0003_expense_fx_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                (
                    'custom_field_data',
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                (
                    'amount',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        validators=[django.core.validators.MinValueValidator(Decimal('0.01'))],
                    ),
                ),
                ('amount_native', models.DecimalField(decimal_places=2, editable=False, max_digits=20)),
                ('fx_rate', models.DecimalField(decimal_places=10, editable=False, max_digits=20)),
                ('date', models.DateField()),
                ('method', models.CharField(blank=True, max_length=30)),
                ('comments', models.TextField(blank=True)),
                (
                    'currency',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='settlements',
                        to='netbox_ledger_tracker.currency',
                    ),
                ),
                (
                    'from_person',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='settlements_paid',
                        to='netbox_ledger_tracker.person',
                    ),
                ),
                (
                    'ledger',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='settlements',
                        to='netbox_ledger_tracker.ledger',
                    ),
                ),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                (
                    'to_person',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='settlements_received',
                        to='netbox_ledger_tracker.person',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Settlement',
                'verbose_name_plural': 'Settlements',
                'ordering': ['-date', '-pk'],
            },
            bases=(netbox_ledger_tracker.models.FrozenRateMixin, netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
